### ISSUE TITLE
Could not find clang

### ISSUE THREAD

**Issue by doronyaary** [EnterpriseDB/system_stats#1]
Hello,

First of all - I would like to say that this is a long awaited extensions for PostgreSQL that really gives important system views for easier monitoring - so thank you for this.

I have tried to install according to instructions but I got an error - I am sure I have done something wrong in the process I just dont know what. These are the steps I have taken (CentOS 7 PG 12) - all with user "root":

```
yum install clang -y
git clone https://github.com/EnterpriseDB/system_stats.git
export PATH=/usr/pgsql-12/bin:$PATH
make install USE_PGXS=1
```

These is the error I got:

```
/opt/rh/llvm-toolset-7/root/usr/bin/clang -Wno-ignored-attributes -fno-strict-aliasing -fwrapv -O2  -I. -I./ -I/usr/pgsql-12/include/server -I/usr/pgsql-12/include/internal  -D_GNU_SOURCE -I/usr/include/libxml2  -I/usr/include -flto=thin -emit-llvm -c -o system_stats.bc system_stats.c
make: /opt/rh/llvm-toolset-7/root/usr/bin/clang: Command not found
make: *** [system_stats.bc] Error 127
```

What have I missed?

Thanks!

**Comment by neel5481** [comment]
Hi,

Here YUM rpm package of postgres which is compiled with LLVM to support JIT with Bitcode so you have to install the llvm toolset packages from scl yum repo because it is not available with core CentOS.

**Comment by doronyaary** [comment]
Hi Neel,

You were 100% accurate! Installing the llvm-toolset-7 did the trick. If anyone is having this issue - this is what solved it for me:

`yum install llvm-toolset-7`

Neel - Cheers!
