### ISSUE TITLE
PostgreSQL 16 support

### ISSUE THREAD

**Issue by devrimgunduz** [EnterpriseDB/system_stats#12]
Hi,

Can you please push a new release for v16 compatibility? It is due tomorrow.

Thanks!

Regards, Devrim

**Comment by neel5481** [comment]
@devrimgunduz Is it giving any issue in compilation against v16 ?

@dpage Do we need to do anything explicitly to support v16 that I am not aware of?

**Comment by devrimgunduz** [comment]
@neel5481 hi. Please see #10

**Comment by neel5481** [comment]
Ah, I get it. Thank you @devrimgunduz 
Added `v2.0` release for v16 support.

**Comment by neel5481** [comment]
Closing this as it is fixed.

**Comment by devrimgunduz** [comment]
Thank you!
