### ISSUE TITLE
Redundant logic.

### ISSUE THREAD

**Issue by xianglin1998** [EnterpriseDB/system_stats#15]
Is it normal to set the value of MaxClockSpeed to l2cache?
Although l2cache was set correctly afterwards.

https://github.com/EnterpriseDB/system_stats/blob/18033e7b4c3553ba655ada855ff029c4e01bbab3/windows/cpu_info.c#L136

**Comment by neel5481** [comment]
yes, you are right, MaxClockSpeed is already getting read before L2CacheSize so removed the redundant code. Below sithe PR ( https://github.com/EnterpriseDB/system_stats/pull/20 )

**Comment by xianglin1998** [comment]
Perfect, thank you.
