### ISSUE TITLE
Memory leak on windows

### ISSUE THREAD

**Issue by xianglin1998** [EnterpriseDB/system_stats#21]
After my test, if function is implement from WMI, the all logic will memory leak after `Get`

VARIANT type need correct `Clear`

Read doc from `Microsoft`, we can get correct fixed. Release function is `VariantClear`.

https://learn.microsoft.com/en-us/windows/win32/api/wbemcli/nf-wbemcli-iwbemclassobject-get
![image](https://github.com/EnterpriseDB/system_stats/assets/23152044/87a05a39-f35c-4985-9cb9-7865717d6f25)

(BTW:  Indeed very few people running commercial databases on Windows.)

**Comment by neel5481** [comment]
Thank you @xianglin1998 WIP PR ( https://github.com/EnterpriseDB/system_stats/pull/22 )

**Comment by xianglin1998** [comment]
Thank you.
