### ISSUE TITLE
Installation problems 

### ISSUE THREAD

**Issue by isik-kaplan** [EnterpriseDB/system_stats#27]
Hey all, I'm here because PgAdmin has a little text saying that I can get more stats if I install system_stats extension but I have no idea how to install this. 

There are some small instructions on the readme file 

```
tar -zxvf system_stats-1.0.tar.gz
cd system_stats-1.0
PATH="/usr/local/pgsql/bin:$PATH" make USE_PGXS=1
sudo PATH="/usr/local/pgsql/bin:$PATH" make install USE_PGXS=1
```

but I'm not sure how to use this, where is this system_stats-1.0.tar.gz file? 

Am I supposed to do/build something to get it first?

I'd love it if someone can lend a helping hand. I also think it'd be a good idea to have the install instructions from scratch somewhere in the repo or in some documentations page (I apologize if it exists and I couldn't find it). 

Let me know if there more in depth instructions somewhere but I couldn't find it.

**Comment by neel5481** [comment]
You should find the latest release code here ( https://github.com/EnterpriseDB/system_stats/releases/tag/v2.1 )
Download and install it against your postresql db.
Thank you.

**Comment by isik-kaplan** [comment]
Hey, thank you. I was able to install using the archive in the release link I was able to install the extension.
