### ISSUE TITLE
sonarqube scan flagged usage of sprintf

### ISSUE THREAD

**Issue by BillSmith-EDB** [EnterpriseDB/system_stats#30]
There are about 14 places where sprintf is use throughout system_stats codebase. The issue is that there's potential for buffer overrun and the suggestion is to use snprintf

Here's one example:
`sprintf(cpu_desc, "%s model %s family %s", vendor_id, model, cpu_family);`

The above snipped could be changed to:
`snprintf(cpu_desc, MAXPGPATH, "%s model %s family %s", vendor_id, model, cpu_family);`

This has actually been done in some other places. It would be good to complete this work.

**Comment by neel5481** [comment]
PR has been raised - https://github.com/EnterpriseDB/system_stats/pull/33

**Comment by neel5481** [comment]
Merged the PR. Thank you.
