### ISSUE TITLE
Build failure against PG17

### ISSUE THREAD

**Issue by sandeep-edb** [EnterpriseDB/system_stats#31]
"Platform is: darwin"
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Werror=vla -Werror=unguarded-availability-new -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -Wno-unused-command-line-argument -g -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX11.sdk -mmacosx-version-min=10.15 -arch x86_64 -arch arm64 -O2  -fvisibility=hidden -I. -I./ -I/opt/pginstaller_17.auto/server/staging_cache/osx.build/include/postgresql/server -I/opt/pginstaller_17.auto/server/staging_cache/osx.build/include/postgresql/internal -I/opt/local/Current_v15/include -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX11.3.sdk  -I/opt/local/20220418/include/libxml2 -I/opt/local/Current_v15/include -I/opt/local/Current_v15/include  -I/opt/local/Current_v15/include/libxml2 -I/opt/local/Current_v15/include -I/opt/local/Current_v15/include/openssl/  -c -o system_stats.o system_stats.c
system_stats.c:131:2: error: implicit declaration of function 'tuplestore_donestoring' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
        tuplestore_donestoring(tupstore);
        ^
system_stats.c:186:2: error: implicit declaration of function 'tuplestore_donestoring' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
        tuplestore_donestoring(tupstore);
        ^
system_stats.c:240:2: error: implicit declaration of function 'tuplestore_donestoring' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
        tuplestore_donestoring(tupstore);
        ^
system_stats.c:294:2: error: implicit declaration of function 'tuplestore_donestoring' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
        tuplestore_donestoring(tupstore);
        ^
system_stats.c:348:2: error: implicit declaration of function 'tuplestore_donestoring' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
        tuplestore_donestoring(tupstore);
        ^
system_stats.c:402:2: error: implicit declaration of function 'tuplestore_donestoring' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
        tuplestore_donestoring(tupstore);
        ^
system_stats.c:457:2: error: implicit declaration of function 'tuplestore_donestoring' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
        tuplestore_donestoring(tupstore);
        ^
system_stats.c:511:2: error: implicit declaration of function 'tuplestore_donestoring' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
        tuplestore_donestoring(tupstore);
        ^
system_stats.c:565:2: error: implicit declaration of function 'tuplestore_donestoring' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
        tuplestore_donestoring(tupstore);
        ^
system_stats.c:619:2: error: implicit declaration of function 'tuplestore_donestoring' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
        tuplestore_donestoring(tupstore);
        ^
10 errors generated.
make: *** [system_stats.o] Error 1

**Comment by neel5481** [comment]
PR has been raised - https://github.com/EnterpriseDB/system_stats/pull/32

Thank you for reporting @sandeep-edb

**Comment by neel5481** [comment]
PR has been merged. Thank you.
