### ISSUE TITLE
make installcheck fails due to missing test file sql/system_stats.sql

### ISSUE THREAD

**Issue by joelonsql** [EnterpriseDB/system_stats#4]
Hi,

It looks like the normal sql/ and expected/ directories are missing.

I get this error when trying to run "make installcheck":

    $ make installcheck
    "Platform is: linux"
    /usr/lib/postgresql/13/lib/pgxs/src/makefiles/../../src/test/regress/pg_regress --inputdir=./ --bindir='/usr/lib/postgresql/13/bin'    --dbname=contrib_regression system_stats
    (using postmaster on Unix socket, default port)
    ============== dropping database "contrib_regression" ==============
    DROP DATABASE
    ============== creating database "contrib_regression" ==============
    CREATE DATABASE
    ALTER DATABASE
    ============== running regression test queries        ==============
    test system_stats                 ... /bin/sh: 1: cannot open /home/joel/postgresql-extensions/system_stats/sql/system_stats.sql: No such file
    diff: /home/joel/postgresql-extensions/system_stats/expected/system_stats.out: No such file or directory
    diff: /home/joel/postgresql-extensions/system_stats/results/system_stats.out: No such file or directory
    diff command failed with status 512: diff  "/home/joel/postgresql-extensions/system_stats/expected/system_stats.out" "/home/joel/postgresql-extensions/system_stats/results/system_stats.out" > "/home/joel/postgresql-extensions/system_stats/results/system_stats.out.diff"
    make: *** [/usr/lib/postgresql/13/lib/pgxs/src/makefiles/pgxs.mk:420: installcheck] Error 2

**Comment by devrimgunduz** [comment]
@neel5481 any updates?

**Comment by dpage-edb** [comment]
There are no regression tests for this module, because the output the functions return is unpredictable so there's no way to create expected output files. If we were to mock the unpredictable parts, the tests would only actually be testing the function definition boilerplate and not the code that does the actual work, which seems like a lot of effort for very little benefit.
